import json
import os
import re
import subprocess

score = 0
reasons = []

# -------------------------
# DUPLICATION ANALYSIS
# -------------------------

duplication_score = 0

try:
    with open("jscpd-report/jscpd-report.json") as f:
        data = json.load(f)

    percentage = data["statistics"]["total"]["percentage"]

    if percentage > 15:
        duplication_score += 25
        reasons.append(f"High duplication detected ({percentage:.2f}%)")

except Exception:
    pass

score += duplication_score

# -------------------------
# COMPLEXITY ANALYSIS
# -------------------------

try:
    with open("lizard-report.txt") as f:
        content = f.read()

    long_functions = len(re.findall(r"\s+[5-9][0-9]\s+[5-9][0-9]", content))

    if long_functions > 10:
        score += 15
        reasons.append("Too many large/complex functions")

except Exception:
    pass

# -------------------------
# TODO/FIXME DENSITY
# -------------------------

todo_count = 0

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith((".js", ".ts", ".py", ".java", ".go")):
            path = os.path.join(root, file)

            try:
                with open(path, errors="ignore") as f:
                    text = f.read()

                todo_count += len(re.findall(r"TODO|FIXME|TEMP", text))

            except:
                pass

if todo_count > 20:
    score += 10
    reasons.append(f"Excessive TODO/FIXME markers ({todo_count})")

# -------------------------
# AI COMMENT PATTERNS
# -------------------------

ai_patterns = [
    r"generated by chatgpt",
    r"auto-generated",
    r"boilerplate",
    r"example implementation",
    r"placeholder implementation",
]

matches = 0

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith((".js", ".ts", ".py", ".java", ".go")):
            path = os.path.join(root, file)

            try:
                with open(path, errors="ignore") as f:
                    text = f.read().lower()

                for pattern in ai_patterns:
                    matches += len(re.findall(pattern, text))

            except:
                pass

if matches > 0:
    score += 20
    reasons.append("AI-generated comment patterns detected")

# -------------------------
# TEST COVERAGE HEURISTIC
# -------------------------

src_files = 0
test_files = 0

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith((".js", ".ts", ".py")):

            if "test" in file.lower():
                test_files += 1
            else:
                src_files += 1

if src_files > 0:
    ratio = test_files / src_files

    if ratio < 0.15:
        score += 20
        reasons.append("Very low test-to-source ratio")

# -------------------------
# LARGE PR DETECTION
# -------------------------

try:
    diff = subprocess.check_output(
        ["git", "diff", "--shortstat", "origin/main"]
    ).decode()

    numbers = re.findall(r"\d+", diff)

    if numbers:
        changed_lines = int(numbers[-1])

        if changed_lines > 1500:
            score += 15
            reasons.append("Huge PR size detected")

except:
    pass

# -------------------------
# COMMIT MESSAGE QUALITY
# -------------------------

try:
    logs = subprocess.check_output(
        ["git", "log", "--pretty=%s", "-n", "10"]
    ).decode().lower()

    weak_msgs = len(
        re.findall(r"fix|update|changes|stuff|final", logs)
    )

    if weak_msgs > 5:
        score += 10
        reasons.append("Low-entropy commit messages")

except:
    pass

# -------------------------
# FINALIZE SCORE
# -------------------------

score = min(score, 100)

risk_level = "LOW"

if score >= 70:
    risk_level = "HIGH"
elif score >= 40:
    risk_level = "MEDIUM"

report = f"""
# Low-Code Risk Analysis

Risk Score: {score}%

Risk Level: {risk_level}

## Findings
"""

if reasons:
    for r in reasons:
        report += f"- {r}\n"
else:
    report += "- No major issues detected.\n"

report += """

## Recommendation

- Review architectural consistency
- Verify business logic manually
- Enforce test quality
- Review for hidden security flaws
"""

with open("low-code-report.txt", "w") as f:
    f.write(report)

print(report)

