name: Slack Notification Workflow

on:
  push:
    branches:
        - '*' # any branch trigger
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send status message to Slack
        uses: slackapi/slack-github-action@v3.0.3  # Official Slack GitHub Action
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.head_commit.url }}"
            }
